env:
  datasets_folder: /media/uv/Data/workspace/HH_gen/tridi/data/preprocessed/
  raw_datasets_folder: /media/uv/Data/workspace/HH_gen/tridi/data/raw/
  assets_folder: /media/uv/Data/workspace/HH_gen/assets/
  experiments_folder: /media/uv/Data/workspace/HH_gen/experiments
  smpl_folder: /media/uv/Data/workspace/HH_gen/tridi/data/smplx_models/
  #datasets_folder: ./data/preprocessed/
  #raw_datasets_folder: ./data/raw/
  #assets_folder: ./assets/
  #experiments_folder: ./experiments
  #smpl_folder: ./data/smplx_models/
